config/routes.rb
Kidsralright::Application.routes.draw do

  root to: "application#flash_page"

  devise_for :users
  devise_scope :user do
    get "/signin", to: "devise/sessions#new"
    get "/signout", to: "devise/sessions#destroy"
  end

  match "/timeline", controller: "timeline", action: "index", via: [:get]
  match "/admin", controller: "admin", action: "index", via: [:get]

  resources :users

  resources :schools do
    resources :classrooms
    resources :students
  end

  resources :classrooms do
    resources :ksrcomments
  end

  resources :schedules do
    resources :ksrcomments
  end

  resources :accounts

  resources :posts
end

app/models/Student.rb
class Student < ActiveRecord::Base
  has_many :guardians

end

app/models/User.rb
# A base STI class: parents, gardian, teacher, director, etc.
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  attr_accessible :email, :first_name, :last_name, :phone

  def full_name
    @full_name ||= [first_name, last_name].join(" ").strip
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  attr_reader :user

  def initialize(user)
    @user = user
    build_permissions
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end

  def build_permissions
    if user.is_director?
      can :manage, :all
    end

    if user.is_teacher?
      can [:read, :create], Post, classroom: {school_id: user.school_ids}
    end
  end

end

app/models/account.rb
class Account < ActiveRecord::Base

  strip_attributes :only => [:name]
  attr_accessible :name
  has_many :schools

end

app/models/activity.rb
class Activity
  include Mongoid::Document

  DEFAULT_ACTIVITY_LIST = %w(
    Art
    Creative Movement
    Math/Science
    Language Development
    Music
    Computer
  )

  field :name, type: String
  field :lessons, type: Array
  field :description, type: String
end

app/models/activity_list.rb
class ActivityList < ActiveRecord::Base
  has_many :activities
  belongs_to :class
end

app/models/activity_template.rb
class ActivityTemplate
  include Mongoid::Document
  include Mongoid::Timestamps
  include Tenacity

  t_belongs_to :classroom
  embeds_many :activities
end

app/models/class_room.rb
class ClassRoom < ActiveRecord::Base
  belongs_to :account
  has_many :students
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  include Tenacity

  attr_accessible :name, :school

  belongs_to :school
  has_many :students
  has_many :users
  has_many :ksr_comments, :as => :commentable
  has_many :schedules
  t_has_one :activity_template

  def comment_for date = Date.today
    self.ksrcomemnts.where(:date_of_comment => date).first
  end
end

app/models/daily_activity.rb
class ActivityTemplate
  include Mongoid::Document
  include Mongoid::Timestamps
  include Tenacity

  t_belongs_to :classroom
  embeds_many :activities

  field :date_of_activity, type: Date
end

app/models/guardian.rb
class Guardian < User
  belongs_to :student
end

app/models/ksrcomment.rb
class Kracomment < ActiveRecord::Base

  strip_attributes :only => [:comment]

  attr_accessible :comment, :date_of_comment, :user

  belongs_to :commentable, :polymorphic => true
  validates_uniqueness_of :commentable, :scope => [:date_of_comment]

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :post
  mount_uploader :image, PhotoUploader
end

app/models/post.rb
class Post < ActiveRecord::Base

  strip_attributes :only => [:message]

  belongs_to :classroom # this essentially is the classroom's whiteboard
  belongs_to :creator, :class_name => 'User'
  has_many :photos

  validate :classroom, :presence => true
  validate :creator, :presense => true
  validate :message, :presence => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, join_table: "users_roles"
  attr_accessible :name
  validate :name, presense: true
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  strip_attributes :only => [:name]
  has_many :schedule_items
  belongs_to :classroom

  after_initialize :set_default_values, :on => :create
  validate :start_date_earlier_than_end_date

  private ##### private #######

  def start_date_earlier_than_end_date
    if self.start_date > self.end_date
      errors.add(:start_date => "can't be later than end date")
    end
  end

  def set_default_values
    self.start_date = Date.today
    self.end_date = Date.today
  end
end

app/models/schedule_item.rb
class ScheduleItem < ActiveRecord::Base

  strip_attributes :only => [:title, :description, :comments]

  default_scope { order(:start_time) }

  belongs_to :schedule
  validates :schedule_id, :start_time, :end_time, :title, :presence => true
  validate :start_time_earlier_than_end_time

  private

  def start_time_earlier_than_end_time
    if start_time > end_time
      errors.add(:start_time, "can't be later than end time")
    end
  end
end

app/models/school.rb
class School < ActiveRecord::Base

  strip_attributes :only => [:name, :address]
  attr_accessible :name, :address, :account

  belongs_to :account
  has_many :students
  has_many :posts
  has_many :classrooms
  has_many :users

  after_create :create_default_activity_list



  private

  # create default activity list, but the user can modify them if necessary
  def create_default_activity_list
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :guardians
  has_many :posts

end

app/models/user.rb
# A base STI class: parents, gardian, teacher, director, etc.
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable

  mount_uploader :avatar, AvatarUploader
  has_and_belongs_to_many :roles, join_table: "users_roles"
  belongs_to :school
  belongs_to :default_classroom, class_name: "Classroom"

  strip_attributes :only => [:email, :first_name, :last_name]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  attr_accessible :email, :first_name, :last_name, :phone

  def full_name
    @full_name ||= [first_name, last_name].join(" ").strip
  end

  # a teacher can access his school's classrooms
  def classrooms
    self.school.classrooms if is_teacher? || is_director?
  end

  def classroom_ids
    self.classrooms.map(&:id)
  end

  def user_roles
    @user_roles ||= self.roles
  end

  # define helper methods for role checking
  def is_director?
    user_roles.include?(director_role)
  end

  def is_teacher?
    user_roles.include?(teacher_role)
  end

  def is_guardian?
    user_roles.include?(guardian_role)
  end

  def director_role
    @director_role ||= Role.find_by_name("director")
  end

  def teacher_role
    @teacher_role ||= Role.find_by_name("teacher")
  end

  def guardian_role
    @guardian_role ||= Role.find_by_name("guardian")
  end
end

app/views/admin/index.html.erb
<script type="text/javascript">
  $(document).ready(function () {
    var adminView = new Kra.Views.Admin();
    $("#admin").html(adminView.el);
  });
</script>
  <div class="row">
    <%= render './sidebar' %>
    <div class="span9">
      <div class="row">
        <div id="admin" class="span9"></div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class='container'>
    <ul class="footer-links">
      <li><a href="/copyright-policy">Copyright Policy</a></li>
      <li><a href="/privacy">Privacy Policy</a></li>
      <li><a href="/security">Security</a></li>
      <li><a href="/tos">Terms of Service</a></li>
      <li><a href="/blog">Blog</a></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "MoziCare", root_path, id: "logo", class: 'brand' %>
      <nav>
        <ul class="nav pull-right">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">Products</a></li>
          <li><a href="#">Contact Us</a></li>
          <li><a href="#">FAQs</a></li>
          <li><a href="#">Support</a></li>
          <li><%= link_to "Home", root_path %></li>
          <%#<li><%= link_to "Help", help_path %></li>
          <li class="divider-vertical"></li>
          <% if user_signed_in? %>
            <!-- <li><%= link_to "Users", users_path %></li> -->
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <title>Kidsralright</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag "application", :media => "all" %>
<!-- >   // <script src="http://code.jquery.com/jquery-migrate-1.1.1.min.js"></script> -->
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>

<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>